# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fff5c8902a3290b0ecc93d93971c20e05f9187f32fd4b720554e1e36bb582dcdca28f172e5a56e96f0bd55358e924da802c38049f52aa8bc9900562e9dab4ba

test:
  secret_key_base: 1f2ab3afadb9c3927f16d243edfbb0624347df5f2c3722017d5c934e8bf955e5ff5deea8f11bbdb36337c119340d61e9c567f28afb250ffc171387a45aeadda5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
